name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'tests/**'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  e2e:
    strategy:
      matrix:
        os: [ ubuntu-latest, ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17 # Need for pnpm >=7.7


      # TODO: Install not all dependencies, but only those required for this workflow
      - name: Install dependencies
        run: npm i -g pnpm && pnpm i

      - run: pnpm test
        if: ${{ false }}  # disable for now
